  -- 1. Revenue generated by male VS female customers?

  select gender, sum(purchase_amount) as revenue
  from customers
  group by gender;


  --2. What is the revenue contribution of each age group? 

  select 
    age_group,
    sum(purchase_amount) as total_revenue
  from customers
  group by age_group
  order by total_revenue desc;

  --3.Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

  select subscription_status,
       count(customer_id) as repeat_buyers
  from customers
  where previous_purchases > 5
  group by subscription_status;

  --4. Which 5 products have the highest percentage of purchases with discounts applied?

  select item_purchased,
       ROUND(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
  from customers
  group by item_purchased
  order by discount_rate DESC
  limit 5;

  --5. Compare the average Purchase Amounts between Standard and Express Shipping. 

  select shipping_type, 
  round(avg(purchase_amount),2)
  from customers
  where shipping_type in ('Standard','Express')
  group by shipping_type;

  --6.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

  select subscription_status,
       count(customer_id) as total_customers,
       round(avg(purchase_amount),2) as avg_spend,
       round(sum(purchase_amount),2) as total_revenue
  from customers
  group by subscription_status
  order by total_revenue,avg_spend desc;

  --7. Which are the top 5 products with the highest average review rating?

  select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
  from customers
  group by item_purchased
  order by avg(review_rating) desc
  limit 5;

  --8.Which customers used a discount but still spent more than the average purchase amount?

  select customer_id, purchase_amount 
  from customers
  where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers)

  --9. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

  with customer_type as (
  select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customers)

select customer_segment,count(*) as "Number of Customers" 
from customer_type 
group by customer_segment;

--10. What are the top 3 most purchased products within each category? 

with item_counts as (
    select category,
           item_purchased,
           count(customer_id) as total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;